from pydantic import BaseModel

class KeplerInferenceFeatures(BaseModel):
    koi_period: float
    koi_time0bk: float
    koi_time0: float
    koi_impact: float
    koi_impact_err1: float
    koi_impact_err2: float
    koi_duration: float
    koi_duration_err1: float
    koi_duration_err2: float
    koi_depth: float
    koi_depth_err1: float
    koi_depth_err2: float
    koi_ror: float
    koi_ror_err1: float
    koi_ror_err2: float
    koi_srho: float
    koi_srho_err1: float
    koi_srho_err2: float
    koi_prad: float
    koi_prad_err1: float
    koi_prad_err2: float
    koi_sma: float
    koi_incl: float
    koi_teq: float
    koi_insol: float
    koi_insol_err1: float
    koi_insol_err2: float
    koi_dor: float
    koi_dor_err1: float
    koi_dor_err2: float
    koi_ldm_coeff2: float
    koi_ldm_coeff1: float
    koi_max_sngle_ev: float
    koi_max_mult_ev: float
    koi_model_snr: float
    koi_count: float
    koi_num_transits: float
    koi_bin_oedp_sig: float
    koi_steff: float
    koi_steff_err1: float
    koi_steff_err2: float
    koi_slogg: float
    koi_slogg_err1: float
    koi_slogg_err2: float
    koi_srad: float
    koi_srad_err1: float
    koi_srad_err2: float
    koi_smass: float
    koi_smass_err1: float
    koi_smass_err2: float
    koi_fwm_stat_sig: float
